### ISSUE TITLE
License file is missing from the repo

### ISSUE THREAD

**Issue by faisalrali10** [davidwhitney/System.Configuration.Abstractions#18]
Hello devs, 

This is really a request and not an issue. I am trying to use your library for our organization but there is no LICENSE file present under the GitHub repo. I know your library is covered by MIT license and per their template https://opensource.org/licenses/MIT you may create a license file by filling out the specific info. May I please request you to create one so that we could use your wonderful library within our application legally?

In case the license file already exists somewhere, would you please provide me with its location?

Thank you,
Faisal

**Comment by davidwhitney** [comment]
Hey - added the license file. Thanks for pointing this out, just an oversight.

**Comment by faisalrali10** [comment]
My pleasure. And thanks for taking care of it so quickly.

Faisal
