### ISSUE TITLE
Uri Converter

### ISSUE THREAD

**Issue by oliversweb** [davidwhitney/System.Configuration.Abstractions#7]
Dave,

I find myself converting Uri entries in the config from strings to 'new Uri(string)' so hoping to perform this naturally within the 'System.Configuration.Abstractions.AppSetting<T>()' method with a simple;

                if (typeof(T) == typeof(Uri))
                    return (T) (object) (new Uri(rawSetting));

Rather than going down the path of supplying a list of Custom Converters, etc., what are you views?

Cheers,

Billy

**Comment by davidwhitney** [comment]
Yeah - makes sense - people will do that a lot and while it's not "primitive" it's a commonly used type.
I might wire it as custom converters internally, but queue up this as one of the defaults - seem sensible?

**Comment by oliversweb** [comment]
Cool, I will prep a pr, ty

**Comment by davidwhitney** [comment]
:+1:

**Comment by oliversweb** [comment]
Pr created https://github.com/davidwhitney/System.Configuration.Abstractions/pull/8
